package exceptionHandling;
/**
 *
 * In try block code below exception statement can ot be executed, directly goes to the catch block and remaining program
 *
 * */
public class TryCatchBlock {
    public static void main(String[] args) {
//        try{
//            int i = 10;
//            System.out.println(i/0);
//        }catch (ArithmeticException ae){
//            ae.printStackTrace();   // shows ExceptionClassName, Description message, Exception Stack trace
//            System.out.println(ae.getStackTrace()); // shows object location not used mostly
//            System.out.println(ae.getMessage());    //shows description only
//            System.out.println("can not divide by 0");  //  custom msg
//            System.out.println(ae); //  shows ExceptionClassName, Description message, Exception Stack trace as msg
//        }

//        try{
//            String name = null;
//            System.out.println(name.length());
//        }catch (Exception e){
//            e.printStackTrace();
//        }
    }
}
